### PR TITLE
Don't turn SSL into lowercase

### LINKED ISSUE #3816: Wings turns all uppercase letters in ssl certificate filename to lowercase
### Is there an existing issue for this?

- [X] I have searched the existing issues before opening this issue.

### Current Behavior

The filename of my ssl certificate and key files contains an uppercase letter, but when staring wings, it complains that it didn't find the certificate file and logs the path all in lowercase.
This is my config
```
    cert: /etc/ssl/certs/domainDotCom_bundle.cer
    key: /etc/ssl/private/domainDotCom_private.key
```
And on the logs this appears
```
wings_1  | FATAL: [Dec 16 17:23:35.324] failed to configure HTTPS server auto_tls=false error=open cert: /etc/ssl/certs/domaindotcom_bundle.cer no such file or directory
wings_1  |
wings_1  | Stacktrace:
wings_1  | open /etc/ssl/certs/domaindotcom_bundle.cer: no such file or directory
wings_1  | github.com/pterodactyl/wings/cmd.rootCmdRun
wings_1  |      github.com/pterodactyl/wings/cmd/root.go:359
wings_1  | github.com/spf13/cobra.(*Command).execute
wings_1  |      github.com/spf13/cobra@v1.2.1/command.go:860
wings_1  | github.com/spf13/cobra.(*Command).ExecuteC
wings_1  |      github.com/spf13/cobra@v1.2.1/command.go:974
wings_1  | github.com/spf13/cobra.(*Command).Execute
wings_1  |      github.com/spf13/cobra@v1.2.1/command.go:902
wings_1  | github.com/pterodactyl/wings/cmd.Execute
wings_1  |      github.com/pterodactyl/wings/cmd/root.go:68
wings_1  | main.main
wings_1  |      ./wings.go:8
wings_1  | runtime.main
wings_1  |      runtime/proc.go:255
wings_1  | runtime.goexit
wings_1  |      runtime/asm_amd64.s:1581

```

### Expected Behavior

if the filename to my ssl certificate contains an uppercase letter, i would expect it to not be turned into lowercase

### Steps to Reproduce

Just have an uppercase letter on the filename of the ssl certificate path

### Panel Version

1.6.6 (i think, running in docker and says its canary)

### Wings Version

1.5.3

### Error Logs

_No response_

### PR DESCRIPTION
**Pull request by ghost**
This pull request fixes pterodactyl/panel#3816.

### CODE REVIEW

**Comment by mrxbox98** [comment]
@TacticalCatto I created a PR on your branch which merges https://github.com/pterodactyl/wings/pull/113 into it that also fixes upper case ssl for letsencrypt files.

File: router/router_system.go [hunk 1]
```diff
@@ -103,15 +102,7 @@ func postUpdateConfiguration(c *gin.Context) {
 	if err := c.BindJSON(&cfg); err != nil {
 		return
 	}
-	// Keep the SSL certificates the same since the Panel will send through Lets Encrypt
-	// default locations. However, if we picked a different location manually we don't
-	// want to override that.
-	//
-	// If you pass through manual locations in the API call this logic will be skipped.
-	if strings.HasPrefix(cfg.Api.Ssl.KeyFile, "/etc/letsencrypt/live/") {
```
Comment (DaneEveritt) [inline router/router_system.go:111]: This code should not have been removed, the comment explains what it was doing, the only change that should have happened was removing the to lower call.

Without this every config update will overwrite any custom SSL configuration the user might have added.

**Review by DaneEveritt — CHANGES_REQUESTED** [review]

**Review by matthewpi — APPROVED** [review]
