### PR TITLE
Minimize blocking in Filesystem.getCachedDiskUsage

### LINKED ISSUE #2287: Disk Size Check blocks console output and other stats
**Background (please complete the following information):**
* Panel or Daemon: daemon
* Version of Panel/Daemon: git v1.0.0-rc.2-9-g3c662d5
* Server's OS: Debian 10
* Your Computer's OS & Browser: Windows 10 / Chrome

**Describe the bug**
When a server has a large amount of files, checking the disk usage takes a good while (2-4 minutes with 14 million files); As a result when stat events are queued for the websocket, it blocks all other events from processing until the sizing is complete.

As a result the console will not update, and CPU / Memory will not update either until the sizing operation is completed.

The disk cache is only good for 2.5 minutes (hardcoded) currently, so every 2.5 minutes the server console appears "locked up" in the front end until the sizing is complete.

**To Reproduce**
1. Fill a server with tons of files (touch in a for loop works well for this)
2. Run server that produces constant output
3. After 2.5 minutes, observe how all updating is locked

**Expected behavior**
When disk sizing becomes stale, I'd expect the console and other stats (Memory / CPU) to continue updating while disk sizing is happening in the background.

### PR DESCRIPTION
**Pull request by cyberkitsune**
This resolves pterodactyl/panel#2287

When the disk size cache expires BUT another process is already refreshing it, just return the stale size instead of locking.

This prevents several other things (namely console updates) from freezing if the disk size process is taking ages.

I added an argument to skip the cache for some processes that we're ok with always blocking (like server startup)

### CODE REVIEW

**Comment by cyberkitsune** [comment]
Don't merge quite yet, covering some additional bases. Feedback welcome still however

**Comment by cyberkitsune** [comment]
This is behaving correctly for me now.

File: server/filesystem.go [hunk 1]
```diff
@@ -43,8 +43,9 @@ func IsPathResolutionError(err error) bool {
 type Filesystem struct {
 	mu sync.RWMutex
 
-	lastLookupTime time.Time
-	diskUsage      int64
+	lastLookupTime   time.Time
+	lookupInProgress bool `default:"false"`
```
Comment (matthewpi) [inline server/filesystem.go]: There is no need for the `default:"false"`, it doesn't do anything.  Also a `bool`'s default value is `false`.

File: server/filesystem.go [hunk 2]
```diff
@@ -43,8 +43,9 @@ func IsPathResolutionError(err error) bool {
 type Filesystem struct {
 	mu sync.RWMutex
```
Comment (matthewpi) [inline server/filesystem.go]: This mutex doesn't seem to be used anywhere else, it could probably be switched to a `sync.Mutex`.

File: server/filesystem.go [hunk 3]
```diff
@@ -238,20 +239,35 @@ func (fs *Filesystem) HasSpaceAvailable() bool {
 // as needed without overly taxing the system. This will prioritize the value from the cache to avoid
 // excessive IO usage. We will only walk the filesystem and determine the size of the directory if there
 // is no longer a cached value.
-func (fs *Filesystem) getCachedDiskUsage() (int64, error) {
+func (fs *Filesystem) getCachedDiskUsage(avoidCache bool) (int64, error) {
+
+	// Expire the cache after 2.5 minutes, and used the last cached value if we're currently sizing.
+	if !avoidCache && (fs.lastLookupTime.After(time.Now().Add(time.Second*-150)) || fs.lookupInProgress) {
+		return fs.diskUsage, nil
```
Comment (matthewpi) [inline server/filesystem.go]: Use `atomic.LoadInt64` when working with `diskUsage` as it is set atomically.

File: server/filesystem.go [hunk 4]
```diff
@@ -238,20 +239,35 @@ func (fs *Filesystem) HasSpaceAvailable() bool {
...
+	// Cache expired, and we're not currently updating it.
+	// If we NEED the value now, block.
+	if avoidCache {
+		return fs.updateCachedDiskUsage()
+	}
+
+	// otherwise trigger the update in the background and return stale value
+	go fs.updateCachedDiskUsage()
+
+	return fs.diskUsage, nil
```
Comment (matthewpi) [inline server/filesystem.go]: Use `atomic.LoadInt64` when working with `diskUsage` as it is set atomically.

File: server/filesystem.go (hunk 3 above)
Comment (matthewpi) [reply server/filesystem.go]: Also reading `fs.lookupInProgress` could cause a race condition as it is set with a lock but this function doesn't use one, it would probably be best to make it an atomic.

File: server/filesystem.go [hunk 5]
```diff
@@ -238,20 +239,35 @@ func (fs *Filesystem) HasSpaceAvailable() bool {
 // as needed without overly taxing the system. This will prioritize the value from the cache to avoid
 // excessive IO usage. We will only walk the filesystem and determine the size of the directory if there
 // is no longer a cached value.
-func (fs *Filesystem) getCachedDiskUsage() (int64, error) {
+func (fs *Filesystem) getCachedDiskUsage(avoidCache bool) (int64, error) {
+
+	// Expire the cache after 2.5 minutes, and used the last cached value if we're currently sizing.
+	if !avoidCache && (fs.lastLookupTime.After(time.Now().Add(time.Second*-150)) || fs.lookupInProgress) {
```
Comment (DaneEveritt) [inline server/filesystem.go]: The `avoidCache` check here is unnecessary and actually causes more problems because it will fall through to the `updateCachedDiskUsage()` call even if the value in the cache is still valid, right? This should also ideally explain why this logic even exists, since the lookup time is clear but the avoid cache and lookup in progress checks aren't as intuitive.

File: server/filesystem.go [hunk 6]
```diff
@@ -238,20 +239,35 @@ func (fs *Filesystem) HasSpaceAvailable() bool {
 // as needed without overly taxing the system. This will prioritize the value from the cache to avoid
 // excessive IO usage. We will only walk the filesystem and determine the size of the directory if there
 // is no longer a cached value.
-func (fs *Filesystem) getCachedDiskUsage() (int64, error) {
+func (fs *Filesystem) getCachedDiskUsage(avoidCache bool) (int64, error) {
```
Comment (DaneEveritt) [inline server/filesystem.go]: I don't think `avoidCache` is a good variable name to describe what it is actually doing here. Perhaps `blockIfStale` or something? Ideally I'd prefer if it didn't even have a parameter being passed through, it feels like something we _should_ be able to check for on our own.

There is always the fun `(...block bool)` trick where we can default to `false` unless someone explicitly calls this with `true`. I'm just worried it is not going to be intuitive to people _how_ to call this function or when they should or should not be passing `true` or `false` if that makes sense.

File: server/filesystem.go [hunk 7]
```diff
@@ -265,6 +281,8 @@ func (fs *Filesystem) getCachedDiskUsage() (int64, error) {
 	fs.lastLookupTime = time.Now()
 	atomic.StoreInt64(&fs.diskUsage, size)
 
+	fs.lookupInProgress = false
```
Comment (DaneEveritt) [inline server/filesystem.go]: For safety, this should probably be a deferred call up where it is set so if this function ever changes or manages to exit early down the road we don't forget to set this back to false.

File: server/loader.go [hunk 8]
```diff
@@ -128,7 +128,7 @@ func FromConfiguration(data *api.ServerConfigurationResponse) (*Server, error) {
 
 	// If the server's data directory exists, force disk usage calculation.
 	if _, err := os.Stat(s.Filesystem.Path()); err == nil {
-		go s.Filesystem.HasSpaceAvailable()
+		go s.Filesystem.HasSpaceAvailable(true)
```
Comment (DaneEveritt) [inline server/loader.go]: This doesn't need to be `true`, it is "forcing" calculation simply so there is a value returned, it doesn't need to be the most accurate value. In this case, we can pass false and not even put this in a go-routine.

File: server/filesystem.go (hunk 6 above)
Comment (DaneEveritt) [reply server/filesystem.go]: Thinking about this more, I'd like if it blocked by default, and only was a non-blocking call in specific cases. Most all of the code was written around that assumption anyways, so making it blocking unless specifically called as a non-blocking operation would make the most sense.

**Review by DaneEveritt — CHANGES_REQUESTED** [review]

**Review by matthewpi — CHANGES_REQUESTED** [review]

File: server/filesystem.go (hunk 6 above)
Comment (cyberkitsune) [reply server/filesystem.go]: I renamed it to "nonBlocking" and described briefly why it exists in the function comments, would that work? :)

**Review by DaneEveritt — APPROVED** [review]
